name: mobile_vision_app_flutter_sdk
description: Flutter SDK for Mobile Vision App
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^1.0.0
  http: ^1.1.0
  tflite_flutter: ^0.10.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
